### ISSUE TITLE
Differences ?

### ISSUE THREAD

**Issue by Sharlaan** [nathanmarks/jss-theme-reactor#2]
Hi
looks like promising lib but i'm wondering what are main differences against other inline JSstylesheet libs like Aphrodite ?
cheers

**Comment by igl** [comment]
This is wrapping JSS.

The difference to Aphrodite are outlined by the JSS author here: https://medium.com/@oleg008/aphrodite-vs-jss-a15761b91ee3#.g3pvlrwug

No IE < 10 support was a bit surprising.
