### ISSUE TITLE
No documentation on SSR?

### ISSUE THREAD

**Issue by kybarg** [nathanmarks/jss-theme-reactor#25]
This plugin is used in `material-ui` and I can't get styles rendered on server. Classes names are applied to blocks but styles are missing. Any help?

**Comment by oliviertassinari** [comment]
The SSR has been documented on the `next` branch: https://material-ui-1dab0.firebaseapp.com/getting-started/server-rendering.

**Comment by kybarg** [comment]
@oliviertassinari sorry, this is outdated issue) just was diving in `material-ui`
