### ISSUE TITLE
Support jss@7?

### ISSUE THREAD

**Issue by oliviertassinari** [nathanmarks/jss-theme-reactor#37]
The signature of `generateClassName` seems to have [changed](https://github.com/cssinjs/jss/blob/master/changelog.md#breaking-changes). I'm not sure it's still compatible.

**Comment by nathanmarks** [comment]
@oliviertassinari wondering if we should also only use the verbose selectors in dev mode, WDYT?

**Comment by oliviertassinari** [comment]
> wondering if we should also only use the verbose selectors in dev mode

Would that mean?
- Easier debug
- Preventing users to rely on the name of generated className

That sounds good to me 👍 .
