### ISSUE TITLE
React is included in published ThemeProvider.js

### ISSUE THREAD

**Issue by jcperez-ch** [nathanmarks/jss-theme-reactor#7]
This is more like a clarification, not sure if this was intended.

But when I install hss-theme-reactor to be used in a vanillaJS project or even in a angularJS project it installs react as dependency:

```js
var _react = require('react');
```

Since the ThemeProvider is a React component.  Wouldn't be good to specify in the readme the dependency to react? So people is aware of the use of react even for angular or vueJS projects.

**Comment by nathanmarks** [comment]
It doesn't install React as a `dependency`, just a `devDependency`.

I'm going to remove the `ThemeProvider` re-export so it isn't in the `index.js` entry point.
